### ISSUE TITLE
Timing of Events / No acceptance

### ISSUE THREAD

**Issue by LoganGregoryH** [ChristopherJamesN/SportsMatch#4]
Once an event has started, if a bet is not accepted by a counter party then the money needs to be refunded to the account. Maybe each event should be tagged to a specific sporting event with a start time similar to DK. I.E. you make the prop and have some sort of drop down which has events going on that are linked to start times?

**Comment by ChristopherJamesN** [comment]
Each event should have a start and an end time, actions are triggered based on event times being hit.

**Comment by ChristopherJamesN** [comment]
Use delayed_job gem to execute tasks at some point in the future.

**Comment by ChristopherJamesN** [comment]
We will need to manually add the ending and start time of each event for now, but in the future we should be able to pull this information from a pro-sports API. The same goes for checking the winners of each contest.

**Comment by ChristopherJamesN** [comment]
Delayed_job gem is currently being used to run processes at times in the future. Right now the default is to start events at 6pm central time and end them at 10:30pm central time. Obviously will need to create more customization in the future for start/end times of events, but right now it will have to be done by hand.

To start running jobs use `heroku run bin/delayed_job start` and to end running jobs in the background use `heroku run bin/delayed_job stop`. Keep in mind this will use up a significant number of free dyno hours since delayed jobs hits the server every 5 seconds.
